cal_home/urls.py
from django.urls import path
from cal_home import views

urlpatterns = [
    path('', views.landing, name ='cal_landing'),
    path('home/', views.home, name ='cal_home'),
    path('test/', views.test, name ='cal_test'),
]

calen/urls.py
from django.urls import path
from calen import views

app_name = 'calen'
urlpatterns = [
    path('calendar/', views.CalendarView.as_view(template_name="calen/calendar.html"), name='calendarhome'),
    path('event/new/', views.event, name='event_new'),
    path('event/edit/<int:event_id>/', views.event, name='event_edit'),
    path('event/delete/<int:event_id>/', views.event, name='delete_event'),
]

django_project/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import path, include
from users import views as user_views

urlpatterns = [
    path('admin/', admin.site.urls),
    #empty path maches with the empty url in the cal_home to make the homepage
    path('', include('cal_home.urls')),
    path('', include('calen.urls')),
    #user app urls
    path('register/', user_views.register, name='register'),
    path('profile/', user_views.profile, name='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='logout.html'), name='logout'),

 
    path('password-reset/',
          auth_views.PasswordResetView.as_view(template_name='password_reset.html'),
          name='password_reset'),
    path('password-reset/done/',
          auth_views.PasswordResetDoneView.as_view(template_name='password_reset_done.html'),
          name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
          auth_views.PasswordResetConfirmView.as_view(template_name='password_reset_confirm.html'),
          name='password_reset_confirm'),
    path('password-reset-complete/',
          auth_views.PasswordResetCompleteView.as_view(template_name='password_reset_complete.html'),
          name='password_reset_complete'),
]

cal_home/models.py
from django.db import models

calen/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Event(models.Model):
    title = models.CharField(max_length=200)
    description = models.TextField()
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()
    #deleted = False

    @property
    def get_html_url(self):
        '''
        if self.deleted==False:
            url = reverse('calen:event_edit', args=(self.id,))
        elif self.deleted==True:
            '''
        url = reverse('calen:event_edit', args=(self.id,))
        return f'<a href="{url}">{self.title}</a>'

    def get_expired_event(self):
        return self.title

'''
    @property
    def get_html_url(self):
        url = reverse('calen:delete_event', args=(self.id,))
        return f'<a href="{url}">{self.title}</a>'
        '''
    

users/models.py
from django.db import models

# Create your models here.

calen/forms.py
from django.forms import ModelForm, DateInput
from calen.models import Event

class EventForm(ModelForm):
    class Meta:
        model = Event
        widgets = {
            'start_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
            'end_time': DateInput(attrs={'type': 'datetime-local'}, format='%Y-%m-%dT%H:%M'),
        }
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        super(EventForm, self).__init__(*args, **kwargs)
        self.fields['start_time'].input_formats = ('%Y-%m-%dT%H:%M',)
        self.fields['end_time'].input_formats = ('%Y-%m-%dT%H:%M',)

users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

#User object
    class Meta:
        model = User
        fields = ['username','email','password1','password2']

cal_home/views.py
from django.shortcuts import render
from django.http import HttpResponse

# Create your views here.
def landing(request):
    return render(request, 'cal_home/landing.html')
def home(request):
    return render(request, 'cal_home/home.html')
def test(request):
    return render(request, 'cal_home/test.html')

calen/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from datetime import datetime, timedelta, date
from django.views import generic
from django.utils.safestring import mark_safe
import calendar
from .models import *
from .utils import Calendar
from .forms import EventForm

# Create your views here.
def index(request):
    return HttpResponse('hello')

class CalendarView(generic.ListView):
    model = Event
    template_name = 'calen/calendar.html'

    def get_context_data(self, **kwargs):
        t = datetime.today()
        context = super().get_context_data(**kwargs)
        d = get_date(self.request.GET.get('month', None))
        calen = Calendar(d.year, d.month)
        calen.setfirstweekday(6)
        html_calen = calen.formatmonth(withyear=True)
        #html_calen = calen.setfirstweekday(6)
        html_calen = html_calen.replace('>%i<'%t.day, '<b><u><mark id="CalenMark" style="background-color:#ff85b4">%i</mark></u></b><'%t.day)
        context['calendar'] = mark_safe(html_calen)
        context['prev_month'] = prev_month(d)
        context['next_month'] = next_month(d)
        return context

def get_date(req_month):
    if req_month:
        year, month = (int(x) for x in req_month.split('-'))
        return date(year, month, day=1)
    return datetime.today()

def prev_month(d):
    first = d.replace(day=1)
    prev_month = first - timedelta(days=1)
    month = 'month=' + str(prev_month.year) + '-' + str(prev_month.month)
    return month

def next_month(d):
    days_in_month = calendar.monthrange(d.year, d.month)[1]
    last = d.replace(day=days_in_month)
    next_month = last + timedelta(days=1)
    month = 'month=' + str(next_month.year) + '-' + str(next_month.month)
    return month


def event(request, event_id=None):
    instance = Event()
    if event_id:
        instance = get_object_or_404(Event, pk=event_id)
        
    else:
        instance = Event()
    '''
    if instance.end_time <= datetime.now():
        instance.delete()
'''
    if "cancel_event" in request.POST:
        return HttpResponseRedirect(reverse('calen:calendarhome'))
    form = EventForm(request.POST or None, instance=instance)
    if request.POST and form.is_valid():
        if "delete_event" in request.POST:
            #event_id = int(request.POST.get('event_id'))
            #event_item = Event.objects.get(id=event_id)
            #event_item.delete()
            #form.delete()
            #instance.deleted = True
            instance.delete()
            return HttpResponseRedirect(reverse('calen:calendarhome'))
        else:
            form.save()
            return HttpResponseRedirect(reverse('calen:calendarhome'))   
    return render(request, 'calen/event.html', {'form':form})

#def check_date_expired(event):

'''
def delete(request):
    if request.method == 'POST':
        form = EventForm(request.POST)
        events = Event.ogbjects.all()
        event_id = int(request.POST.get('event_id'))
        event_item = Event.objects.get(id=event_id)
        event_item.delete()
        return render(request, 'calen/event.html', {'form':form, 'event':events})
'''

users/views.py
"""NOTE: Our paths do not require 'users/' for some reason. """

from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm

def register(request):
        if request.method == 'POST':
            form = UserRegisterForm(request.POST)
            if form.is_valid():
                form.save()
                username = form.cleaned_data.get('username')
                messages.success(request, f'Your account has been created! You are now able to Log In!')
                return redirect('login')
        else:
            form = UserRegisterForm()
        return render(request, 'register.html', {'form': form})

@login_required
def profile(request):
    return render(request,'profiles.html')

cal_home/templates/cal_home/base.html
{% load static %}
<!DOCTYPE html>

<html>
<head>
     <!-- Required meta tags -->
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

     <link rel="stylesheet" type="text/css" href="{% static '/cal_home/main.css' %}">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css">
      <link rel="stylesheet" type="text/css" href="{% static 'cal_home/calen-style.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'cal_home/home.css' %}">
      <title>Task Scheduler</title>

</head>
<body onload = "useQuote();">
 


  <meta name="viewport" content="width=device-width, initial-scale=1">
  <div class="topnav">
    <!---->
    <a class="active" href={% url 'cal_home' %}>Home</a>
    <a href={% url 'calen:calendarhome' %}>Calendar</a>
    <a href="#Tasks">Tasks</a>
    <a href="#Music">Music</a>
    <a href="#Settings">Settings</a>
   
    
        <button style="float:none" class="quotebtn" onclick="openForm();">Custom Quote</button>
    <div style="float:none" id ="quoteDisplay" class = "quoteDisplay"><p><al>Click the button for a quote.</al></p></div>
    <!-- Implement procedure to log out, maybe add a confirmation window/message before logging out?-->
    <a style="float:right" class="logout" href={% url 'cal_landing' %}>Log Out</a>

  </div>


  <form class = "form-popup" id ="CustomQuote" onsubmit="addQuotes();">
    <form action="/action_page.php" class="form-container">
    <p>Got a quote in your head? Type it in to use it here!</p>
    <input type="text" class = "txtq" placeholder="Enter a quote." id="quote" name = "quotePut">
    <input class="btnm"  type="reset" value="Clear form" />
    <input class="btnm" type="submit" value="Submit now" onclick="saveQuoteForm();"/>
    <button class ="btnm" style="float:none" onclick="newQuote(); saveQuote(); closeForm()">Random</button>
    <button type="button" class="btnm" onclick="closeForm()">Close</button>
      </form>
</form>
      

    <div class ="main-container">
        {% block content %}
          
        {% endblock %}
       
    </div>


    <script type="text/javascript" src="{% static 'cal_home/javascript.js' %}"></script>
    <script type="text/javascript">
      function useBgColor() {
        var x = localStorage.getItem("bgcolor");
        
        document.getElementById("CalenTable").style.backgroundColor = x.value;
   }</script>
    
</body>

</html>

cal_home/templates/cal_home/home.html
{% extends 'cal_home/base.html' %}
<!DOCTYPE html>


{% load static %}

<html>
<head>
    
      <title>Home</title>

</head>

<body onload = "useBgColorH();">
{% block content %}


<div class="container" id="containerHome" >
    <button style="float:none" id="settingsbtn" onclick="openFormB();">Customize</button>
    <form class = "form-popup2" id ="settingsHome">
        <form action="/action_page.php" class="form-container">
        <p>Customize your home page here.</p>
        <p><label for="colorHomeBG">Homepage Background:</label>
            <input type="color" id="colorHome" onchange="clickColorBackH();" value="#cfe5ee"></p>
            <p><label for="colorborderBG">Homepage Border:</label>
                <input type="color" id="colorB" onchange="clickColorB();" value="#8a2be2"></p>
                <p><label for="colorbutton">Buttons:</label>
                    <input type="color" id="colorBu" onchange="clickColorBu();" value="#69e6d1"></p>
                    <p><label for="colorbuttonT">Button Text:</label>
                        <input type="color" id="colorBuT" onchange="clickColorBuT();" value="#1c7987"></p>
        <button type="button" id="closebtnm" class="btnm" onclick="closeFormB();">Save Changes & Close</button>
          </form>
    </form>
     
     <a class ="icon1" id = "icon1" type="button" href= {% url 'calen:calendarhome' %}><img src= "{% static 'cal_home/calen1.png' %}"></img>Calendar<br></a>
    
 
         
    <a class ="icon2" id = "icon2" type="button" href="#Tasks"><img src= "{% static 'cal_home/calen2.png' %}"></img>Tasks<br></a>
    
 
 
        
    <a class="icon3"id = "icon3"  type="button" href="#Music"><img src= "{% static 'cal_home/calen3.png' %}"></img>Music<br></a>
 
        
    <a class="icon4" id = "icon4" type="button" href="#Settings"><img src= "{% static 'cal_home/calen4.png' %}"></img>Settings<br></a>
   

    <script type="text/javascript">
     function clickColorBackH(){
        var x = document.getElementById("colorHome");
        var b;
        document.getElementById("containerHome").style.backgroundColor = x.value;
        b = rgb2hex(document.getElementById("containerHome").style.backgroundColor);
        document.getElementById("colorHome").value = b;
        localStorage.setItem = ("homebgc", x);
    }

    function clickColorB(){
        var x = document.getElementById("colorB");
        var b;
        document.getElementById("containerHome").style.borderColor = x.value;
        b = rgb2hex(document.getElementById("containerHome").style.borderColor);
        document.getElementById("colorB").value = b;
        localStorage.setItem = ("homebgb", x);
    }

    
    function clickColorBu(){
        var x = document.getElementById("colorBu");
        var b;
        document.getElementById("icon1").style.backgroundColor = x.value;
        document.getElementById("icon2").style.backgroundColor = x.value;
        document.getElementById("icon3").style.backgroundColor = x.value;
        document.getElementById("icon4").style.backgroundColor = x.value;
        document.getElementById("settingsbtn").style.backgroundColor = x.value;
        document.getElementById("settingsHome").style.backgroundColor = x.value;
        document.getElementById("closebtnm").style.backgroundColor = x.value;
        b = rgb2hex(document.getElementById("icon1").style.backgroundColor);
        document.getElementById("colorBu").value = b;
        localStorage.setItem = ("homebgbu", x);
    }

    function clickColorBuT(){
        var x = document.getElementById("colorBuT");
        document.getElementById("icon1").style.color = x.value;
        document.getElementById("icon2").style.color = x.value;
        document.getElementById("icon3").style.color = x.value;
        document.getElementById("icon4").style.color = x.value;
        localStorage.setItem = ("homebgbT", x);
    }
    

     function useBgColorH() {
          var x = localStorage.getItem("homebgc");
          var y = localStorage.getItem("homebgb");
          var z = localStorage.getItem("homebgbu");
          var a = localStorage.getItem("homebgbT");
          if (localStorage.getItem("homebgc") != null) {
            document.getElementById("containerHome").style.backgroundColor = x.value;
    document.getElementById("containerHome").style.borderColor = y.value;
    document.getElementById("icon1").style.backgroundColor = z.value;
        document.getElementById("icon2").style.backgroundColor = z.value;
        document.getElementById("icon3").style.backgroundColor = z.value;
        document.getElementById("icon4").style.backgroundColor = z.value;
        document.getElementById("settingsbtn").style.backgroundColor = z.value;
        document.getElementById("settingsHome").style.backgroundColor = z.value;
        document.getElementById("closebtnm").style.backgroundColor = z.value;
        document.getElementById("containerHome").style.Color = a.value;
}
else{
    document.getElementById("containerHome").style.backgroundColor = white;
    document.getElementById("containerHome").style.borderColor = black;
    document.getElementById("icon1").style.backgroundColor = white;
        document.getElementById("icon2").style.backgroundColor = white;
        document.getElementById("icon3").style.backgroundColor = white;
        document.getElementById("icon4").style.backgroundColor = white;
        document.getElementById("settingsbtn").style.backgroundColor = white;
        document.getElementById("settingsHome").style.backgroundColor = white;
        document.getElementById("closebtnm").style.backgroundColor = white;
        document.getElementById("containerHome").style.Color = black;
}

     }
     var hexDigits = new Array
        ("0","1","2","3","4","5","6","7","8","9","a","b","c","d","e","f"); 

//Function to convert rgb color to hex format
function rgb2hex(rgb) {
 rgb = rgb.match(/^rgb\((\d+),\s*(\d+),\s*(\d+)\)$/);
 return "#" + hex(rgb[1]) + hex(rgb[2]) + hex(rgb[3]);
}

function hex(x) {
  return isNaN(x) ? "00" : hexDigits[(x - x % 16) / 16] + hexDigits[x % 16];
 }
     </script>

</div>

{% endblock %}
    </body>

</html>

cal_home/templates/cal_home/landing.html
{% load static %}
<!DOCTYPE html>
<html>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="{% static 'cal_home/style.css' %}"">
    <!--import 'cal_home/style.css'></import-->

    <title>Task Scheduler</title>

{% block content %}
<body>
<div>

<div class = "hero">
    <div class = "feature-arrow" style="margin-top: 50px;"> 
        <a type="button" href="#features">
            <img src="{% static '/cal_home/featuresarrow.png' %}">
        </a>
    </div>
   <div class = "form-box">
       <div class = "image-icons">
        <img src="{% static '/cal_home/calendarpic1.jpg' %}">
        </div>
    <p>
    <h1 class ="home_title">Organize your tasks!</h1> <br>
    </p>
        <div class = "button-box">
            <div id="btn"></div>
            <!-- Buttons will lead to respective pages once they are complete-->
            <a type="button" class= "toggle-btn1" href="{% url 'login' %}">Log In</a>
            <a type="button" class= "toggle-btn2" href="{% url 'register'%}">Sign Up</a>
         </div>
         <div class="image-icons">
             <img src= "{% static '/cal_home/calendarpic2.png' %}">
        </div>
    </div>

<div class="container">

   <h2 id="features"> Features</h2>
    <div class = "about1" >
    
        <a button class="btn" href="#calendar" ><img src= "{% static '/cal_home/calen1.png' %}"></img></a>
    <h1>Calendar<br></h1>
<p class = "p-about">Schedule tasks using this dynamic calendar!</p>
    </div>

    <div class = "about2">

        <a button class="btn" href="#about" ><img src= "{% static '/cal_home/calen2.png' %}"></img></a>
        <h1>Tasks<br></h1>
        <p class = "p-about">Write down tasks so you don't forget!</p>
    </div>


    <div class = "about3">

        
        <a button class="btn" href="#music" ><img src= "{% static '/cal_home/calen3.png' %}"></img></a>
   <h1>Music<br></h1>
   <p class = "p-about">Listen to something while you schedule tasks!</p>
</div>

    <div class = "about4">

        <a button class="btn" href="#settings" ><img src= "{% static '/cal_home/calen4.png' %}"></img></a>
        <h1>Settings<br></h1>
        <p class = "p-about">Make your task scheduler to your liking!</p>
    </div>




</div>


<div id ="calendar" class = "calendar">
    <div class = "start-calendar">
    <h1> Schedule your Tasks: </h1>
<p class = "welcome-to-calendar"> Introducing a dynamic calendar to schedule tasks on.<br><br>
    We make scheduling tasks easy, fun, and reliable.<br>
    Add, edit, and delete at will!<br>
    You will get constant reminders to work on your task. <br>
  </p>
</div>
</div>


<div  id = "about" class = "static">
    <div class = "start-about">
        <h1> Organize yourself with a To Do List: </h1>
    <p class = "welcome-to-about"><br>
        Never miss another task! Just add it to your calendar.<br><br>
        Schedule more than one task! Keep all of your tasks organized. <br>
        Keep track of your own tasks, or your team's progress with this list.<br>
      </p>
    </div>
    </div>
    
    
      <div id ="music" class = "music">
        <div class = "start-music">
        <h1> Listen to music: </h1>
    <p class = "welcome-to-music">Listen to your favorite tunes.<br><br>
        Make scheduling fun by listening to music.<br>
        You can put your favorite songs or some concentrating music to stay on task.<br>
      </p>
    </div>
    </div>

    <div id ="settings" class = "settings">
        <div class = "start-settings">
        <h1> Customize with a variety of settings: </h1>
    <p class = "welcome-to-settings">Change your task scheduler to suit your tastes.<br><br>
        Select a variety of color accents.<br>
        Don't like the way some things work? You can change those too.<br>
        Set your page to define <i>you.</i><br>
      </p>
    </div>
    </div>


    </div>

</body>
{% endblock content %}
</html>

cal_home/templates/cal_home/test.html
<!DOCTYPE html>
{% load static %}
<html>

{% block content %}
	<link rel="preload" href="../index.js" as="script"></link>
<head>
	<title>Testing Page</title>
	<meta charset="UTF-8" />
</head>

<body>
	<div id ="title">Dynamic Calendar Placeholder</div>
	<div id="app"></div>

	<script type='text/javascript' src="./index.js"></script>


</body>


{% endblock content %}


</html>

calen/templates/calen/calendar.html
<!-- calen/templates/calen/calendar.html -->

{% extends 'cal_home/base.html' %}

{% block content %}
<div class ="calenbody">
<div class="clearfix">
    <div class="sidenav">
        <h><u>Notes</u></h>
        <p>Crossed out events have passed</p>
        <p>Events are in order of when they were made not their times</p>
        <p>Highlighted events can be edited and deleted</p>
        <p><u>Customize Your Calendar Colors</u></p> 
        <p><label for="colorBackground">Calendar's Background:</label>
        <input type="color" id="colorBackground" onchange="clickColorBack(); saveBgColor();" value="#e2ffec"></p>
        <p><label for="colorBorder">Calendar's Border:</label>
        <input type="color" id="colorBorder" onchange="clickColorBorder()" value="#ffbe78"></p>
        <p><label for="colorText">Calendar's Text:</label>
        <input type="color" id="colorText" onchange="clickColorText()" value="#000000"></p>
        <p><label for="colorMark">Calendar's Mark:</label>
        <input type="color" id="colorMark" onchange="clickColorMark()" value="#ff85b4"></p>
    </div>
    <div class="main">
        <a style="font-weight:bold" class="btn btn-info left" href="{% url 'calen:calendarhome' %}?{{prev_month}}">Previous Month</a>
        <a style="font-weight:bold" class="btn btn-info right" href="{% url 'calen:calendarhome' %}?{{next_month}}">Next Month</a>
        <a style="font-weight:bold" class="btn btn-info right" href="{% url 'calen:event_new' %}">New Event</a>
       
        {{ calendar  }}
        
    </div>
    
</div>

<script type="text/javascript">

    function clickColorBack(){
        var root = document.documentElement;
        var x = document.getElementById("colorBackground").value;
        var tab = document.getElementById("CalenTable");
        var trs = tab.getElementsByTagName("tr");
        var tds = tab.getElementsByTagName("td");
        for(var i = 0, j = trs.length; i < j; ++i){
            trs[i].style.backgroundColor.innerHTML=x;
        }
        for(var i = 0, j = tds.length; i < j; ++i){
            tds[i].style.backgroundColor.innerHTML=x;
        }
        root.style.setProperty("--backcol", x);
    }

    

    function saveBgColor() {
        var x = document.getElementById("CalenTable");
        x.value = document.getElementById("CalenTable").style.backgroundColor;
     localStorage.setItem("bgcolor", x);
    }

  

    function clickColorBorder(){
        var x = document.getElementById("colorBorder").value;
        var tab = document.getElementById("CalenTable");
        var trs = tab.getElementsByTagName("tr");
        var tds = tab.getElementsByTagName("td");
        for(var i = 0, j = trs.length; i < j; ++i){
            trs[i].style.borderColor=x;
        }
        for(var i = 0, j = tds.length; i < j; ++i){
            tds[i].style.borderColor=x;
        }
    }
    function clickColorText(){
        var x = document.getElementById("colorText").value;
        document.getElementById("CalenMark").style.color=x;
        var tab = document.getElementById("CalenTable");
        var trs = tab.getElementsByTagName("tr"); 
        var tds = tab.getElementsByTagName("td");
        for(var i = 0, j = trs.length; i < j; ++i){
            trs[i].style.color=x;
        }
        for(var i = 0, j = tds.length; i < j; ++i){
            tds[i].style.color=x;
        }
        
    }
    function clickColorMark(){
        var x = document.getElementById("colorMark").value;
        document.getElementById("CalenMark").style.backgroundColor=x;
    }
    
 
</script>

</div>

{% endblock %}

calen/templates/calen/event.html
{% extends 'cal_home/base.html' %}

{% block title %}
Event
{% endblock %}

{% block content %}
{% if form.errors %}
    {% for field in form %}
        {% for error in field.errors %}
            <div class="alert alert-danger">
                {{ field.label }} <strong>{{ error|escape }}</strong>
            </div>
        {% endfor %}
    {% endfor %}
    {% for error in form.non_field_errors %}
        <div class="alert alert-danger">
            {{ field.label }} <strong>{{ error|escape }}</strong>
        </div>
    {% endfor %}
{% endif %}

<form method="post" style="margin-top: 20px;">
    {% csrf_token %}
    <div class="eventnote">
        <h><u>Notes</u></h>
        <p>Start time should be written as: MM/DD/YYYY hr:min AM/PM</p>
        <p><h2>Ex:</h2>05/05/2021 03:45 PM</p>
        <p>End time is written in the same way</p>
    </div>
    <table class="form form-table">
        {{form}}
        <tr>
            <td><button type="submit" name="delete_event" class="btn btn-info right">Delete</button></td>
            <td colspan="2"><button type="submit" class="btn btn-info right">Submit</button></td>
        </tr>
    </table>
</form>

{% endblock %}

users/templates/login.html
{% load static %}

{% load crispy_forms_tags %}
<!DOCTYPE html>
<html style="height:auto;" >
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" type="text/css" href="{% static '/cal_home/style.css' %}">
    <title>Task Scheduler</title>

{% block content %}
<body style="height:auto;">
<div>

<div class = "hero">
   <div class = "form-box">
       <div class = "image-icons">
        <img src="{% static '/cal_home/calendarpic1.jpg' %}">
        </div>
    <p>
    <h1 class ="home_title">LOGIN</h1> <br>
    </p>
        <div class = "">
          <form method="POST">
            {% csrf_token %}
        
            <fieldset class="form-group"><br>
              <center>{{ form|crispy }}<!--Using django's crispy_forms to help front end--></center><br>
        
            <center><br>

            <div class="form-group">
              <button class="button-box">Login</button>
                <a href="{% url 'password_reset' %}">Forgot Password? </a>
            </div>
            </center><br>
            </fieldset>

          </form>
          <div class="border-top pt-3">
            <center>
              <h3 class="text-muted" style="margin-top: 75px;">
                Need An Account: <a class "ml-2" href="{% url 'register' %}">Sign Up Now</a>
              </h3>
        
              <br>
              
              <h3 class="text-muted">
                Back to Home:       <a class "ml-2" href="{% url 'cal_landing' %}">Home Page</a>
              </h3>
            </center>
          </div>
        
        </div>
    </div>

  </body>  
  {% endblock content %}

  </html>
  

users/templates/logout.html
{% extends 'base.html' %}
{% block content %}
  <h2>You have been logged out</h2>
  <div class="border-top pt-3">
      <small class="text-muted">
      <a href="{% url 'login'%}">Log In Again</a>
      </small>
  </div>
{% endblock content %}

users/templates/password_reset.html
{% load crispy_forms_tags %}
<div class="content-section">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Reset Password</Legend>
      {{ form|crispy }}<!--Using django's crispy_forms to help front end-->
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Request Password Reset</button>
    </div>
  </form>
</div>

users/templates/password_reset_complete.html
{% block content %}
  <div class="alert alert-info">
    Your password has been set.
  </div>
  <a href="{% url 'login' %}">Sign In Here </a>
{% endblock content %}

users/templates/password_reset_confirm.html
{% load crispy_forms_tags %}
<div class="content-section">
  <form method="POST">
    {% csrf_token %}
    <fieldset class="form-group">
      <legend class="border-bottom mb-4">Reset Password</Legend>
      {{ form|crispy }}<!--Using django's crispy_forms to help front end-->
    </fieldset>
    <div class="form-group">
      <button class="btn btn-outline-info" type="submit">Reset Password</button>
    </div>
  </form>
</div>